// Code generated by github.com/mazei513/string-map-gen, DO NOT EDIT.
package example

import "errors"

func ToRobot(s string) (robot, error) {
	m := map[string]robot{
		"Chicken": robot_Chicken,
		"Cow":     robotCow,
		"R2D2":    robot_R2D2,
		"C3P0":    robot_C3P0,
	}
	v, ok := m[s]
	if !ok {
		var zero robot
		return zero, errors.New("invalid string")
	}
	return v, nil
}
