package generator

import "text/template"

var tpl = template.Must(template.New("generated").
	Parse(`
// Code generated by github.com/mazei513/string-map-gen, DO NOT EDIT.
package {{.Package}}

func To{{.Name}}(s string) ({{.TypeName}}, error) {
	m := map[string]{{.TypeName}}{
		{{range .Items}}"{{.Key}}": {{.Value}},
		{{end}}
	}
	v, ok := m[s]
	if !ok {
		var zero {{.TypeName}}
		return zero, errors.New("invalid string")
	}
	return v, nil
}
`))
